# Site
repository: loicdiridollou.github.io
favicon: images/favicon.ico

# Personal info
name: Loic Diridollou
title: MFE Student at UC Berkeley - Class of 2021
email: loic_diridollou@mfe.berkeley.edu
website: loicdiridollou.github.io

# Social links
twitter_username: loicdiridollou
github_username:  loicdiridollou
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: loic_diri
linkedin_username: loicdiridollou
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Prior to the MFE, Loic studied statistics and economics at ENSAE Paris where he developed solid skills in stochastic calculus, probability, econometrics, and machine learning using different languages (Python, R and C++). He also holds an associate degree in law from Paris I Panthéon-Sorbonne University.
  His internship experience includes asset management, equity trading and quantitative research. While at the Dutch investment bank Kempen, he worked on several data science and machine learning projects to help traders identify signals. Then, in a quantitative research role at EY Advisory, he was responsible for developing and calibrating a local volatility model that improved option pricing precision as well as working on call-spread options P&L calculations and client engagements for major French banks.
  Loic enjoys exploring innovative methodologies with machine learning such as evolution strategies for trading and deep learning for options pricing. He also has a keen interest in systematic trading and quantitative strategies. Loic spends his free time reading economic news and studying geopolitics; he is also a longtime sailor and sailing instructor.

  
  I am most skilled in: <mark>Python</mark> and <mark>Machine Learning</mark>


# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# Projects Section
# projects_title: Projects


# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in data science and machine learning some of my other interests and hobbies are:
  - Sailing
  - Photography
  - Geopolitics


# Footer
footer_show_references: true

# Build settings
#remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
